apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: staging
data:
  master.cnf: |
    [mysqld]
    server-id=1
    log-bin=mysql-bin
    binlog-do-db=appdb
    datadir=/data
    default_authentication_plugin=mysql_native_password
 
  slave.cnf: |
    [mysqld]
    server-id=2
    replicate-do-db=appdb
    datadir=/data
    default_authentication_plugin=mysql_native_password