apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-slave
  namespace: staging
spec:
  serviceName: mysql-slave
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      role: slave
  template:
    metadata:
      labels:
        app: mysql
        role: slave
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /data
        - name: config-volume
          mountPath: /etc/mysql/conf.d
        readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-uroot", "-p$(MYSQL_ROOT_PASSWORD)"]
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
      - name: config-volume
        configMap:
          name: mysql-config
          items:
            - key: slave.cnf
              path: slave.cnf
      - name: mysql-data
        hostPath:
          path: "/mnt/backup"